### PR TITLE
Feat/11_when_sol_eclipse

### PR DESCRIPTION
**Pull request by nkabembo**
Added Unit Testing with when Solar Eclipse  is

### CODE REVIEW

**Review by nmiles01 — CHANGES_REQUESTED** [review]
does not belong in control.py but I think amy is going to make a folder to put unit tests in

**Review by nkabembo — COMMENTED** [review]
I have added the unit tests in separate folder now shows results of test and output from function

**Comment by FreddieBanfield** [comment]
I have just pushed some changes, I won't be able to peer review. These changes cleaned up the code dramatically (unrelated to this PR changes). Please may someone on VScode try it out and make sure the tests work.

**Review by mattTara — APPROVED** [review]

**Comment by FreddieBanfield** [comment]
Works on Spyder again, please may someone see if both application and tests work on VS Code

**Review by nmiles01 — APPROVED** [review]

**Pull request merged**
