### PR TITLE
Implemented Days until next full moon

### PR DESCRIPTION
**Pull request by Logan-Campbell**

### CODE REVIEW

**Comment by FreddieBanfield** [comment]
Please make a unit test that checks a lunar eclipse in the far future.

**Comment by FreddieBanfield** [comment]
Good job, please may you either add some comments to help with readability, especially for the variable names that are acronyms, or write a document in confluence about this code to help future developers. #

**Review by FreddieBanfield — CHANGES_REQUESTED** [review]
I notice you have written this code within the main controller, if it's possible please may you move your code to a new controller that will handle lunar to avoid one controller doing more than one thing.

NOTE: DIscussed in Thursday meeting, we will make a future refactor ticket to change this. Ignore it for this PR

**Review by FreddieBanfield — CHANGES_REQUESTED** [review]
Good job, please may you either add some comments to help with readability, especially for the variable names that are acronyms, or write a document in confluence about this code to help future developers.

**Review by FreddieBanfield — CHANGES_REQUESTED** [review]
Please may you write a unit test that tests the next full moon from a hardcoded date.

**Review by FreddieBanfield — APPROVED** [review]

**Review by MellowYeller — APPROVED** [review]

**Review by Michael2622 — APPROVED** [review]

**Pull request merged**
